"""PDF and LaTeX export for EIA reports.

Generates clean, professional Environmental Assessment documents
from the structured report JSON produced by the report synthesis agent.
"""

import io
import re
from datetime import datetime

from fpdf import FPDF


# ── Shared helpers ──────────────────────────────────────────────────────────

def _strip_markdown(text: str) -> str:
    """Convert markdown to plain text for PDF rendering."""
    # Bold/italic
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'\1', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    # Headers (keep text)
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    # Links
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
    # Inline code
    text = re.sub(r'`([^`]+)`', r'\1', text)
    # Blockquote markers
    text = re.sub(r'^>\s?', '', text, flags=re.MULTILINE)
    # List bullets — normalize to dash
    text = re.sub(r'^[\*\-]\s+', '- ', text, flags=re.MULTILINE)
    return text


def _get_report(data: dict) -> dict | None:
    """Extract the first report object from the export payload."""
    reports = data.get("reports") or []
    if not reports:
        return None
    return reports[0]


# ── PDF generation ──────────────────────────────────────────────────────────

class _EIAPDF(FPDF):
    """Custom PDF subclass with EIA header/footer."""

    def __init__(self, project_name: str = "EIA Report"):
        super().__init__()
        self._project_name = project_name
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, self._project_name, align="L")
        self.cell(0, 6, "Environmental Assessment", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_pdf(data: dict) -> bytes:
    """Generate a professional EIA PDF from report data. Returns PDF bytes."""
    report = _get_report(data)
    if not report:
        raise ValueError("No report data found")

    meta = report.get("metadata", {})
    sections = report.get("sections", [])
    disclaimer_items = report.get("disclaimer_items", [])

    project_name = "Environmental Assessment"
    # Try to extract project name from title page section
    for s in sections:
        if s.get("section_number") == "1" and s.get("content"):
            content = s["content"]
            match = re.search(r'\*\*Project:\*\*\s*(.+)', content)
            if match:
                project_name = match.group(1).strip()
                break

    pdf = _EIAPDF(project_name=project_name)
    pdf.alias_nb_pages()

    # ── Cover page ──────────────────────────────────────────────────
    pdf.add_page()
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, "Environmental Assessment", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_draw_color(60, 60, 60)
    pdf.line(60, pdf.get_y(), pdf.w - 60, pdf.get_y())
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, project_name, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)

    framework = f"{report.get('framework_id', 'NEPA')} {report.get('document_type', 'EA')}"
    pdf.cell(0, 6, f"Framework: {framework}", align="C", new_x="LMARGIN", new_y="NEXT")

    gen_date = meta.get("generated_at", "")
    if gen_date:
        try:
            dt = datetime.fromisoformat(gen_date.replace("Z", "+00:00"))
            gen_date = dt.strftime("%B %d, %Y")
        except (ValueError, TypeError):
            pass
    pdf.cell(0, 6, f"Generated: {gen_date}", align="C", new_x="LMARGIN", new_y="NEXT")

    model = meta.get("llm_model_used", "")
    if model:
        pdf.cell(0, 6, f"Model: {model}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(0, 5,
        "This document was generated by an automated environmental screening "
        "system. All determinations should be reviewed by a qualified "
        "environmental professional before use in regulatory submissions.",
        align="C")

    # ── Table of Contents ───────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "Table of Contents", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(50, 50, 50)
    for s in sections:
        num = s.get("section_number", "")
        title = s.get("section_title", "Untitled")
        pdf.cell(0, 7, f"  {num}.  {title}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Sections ────────────────────────────────────────────────────
    for s in sections:
        num = s.get("section_number", "")
        title = s.get("section_title", "Untitled")
        content = s.get("content", "")
        highlights = s.get("low_confidence_highlights", [])

        pdf.add_page()

        # Section heading
        pdf.set_font("Helvetica", "B", 15)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 10, f"{num}. {title}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(180, 180, 180)
        pdf.line(10, pdf.get_y(), pdf.w - 10, pdf.get_y())
        pdf.ln(6)

        # Section body
        plain = _strip_markdown(content)
        _render_text_block(pdf, plain)

        # Low-confidence highlights
        if highlights:
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(180, 120, 0)
            pdf.cell(0, 7, "Low Confidence Items:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(140, 100, 0)
            for h in highlights:
                conf = round((h.get("confidence", 0)) * 100)
                excerpt = h.get("text_excerpt", "")
                pdf.multi_cell(0, 5, f"  [{conf}%] {excerpt}")
                pdf.ln(1)

    # ── Disclaimer appendix ─────────────────────────────────────────
    if disclaimer_items:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 15)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 10, "Items Requiring Human Review", new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(180, 180, 180)
        pdf.line(10, pdf.get_y(), pdf.w - 10, pdf.get_y())
        pdf.ln(6)

        for item in disclaimer_items:
            cat = (item.get("category", "") or "").replace("_", " ")
            det = item.get("determination", "")
            conf = round((item.get("confidence", 0)) * 100)
            reasoning = item.get("reasoning", "")

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(0, 6, f"{cat} — {det} ({conf}% confidence)",
                     new_x="LMARGIN", new_y="NEXT")

            if reasoning:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.multi_cell(0, 5, f"  {reasoning}")
            pdf.ln(3)

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()


def _render_text_block(pdf: FPDF, text: str):
    """Render a block of plain text, handling paragraphs and list items."""
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)

    paragraphs = re.split(r'\n{2,}', text.strip())
    for para in paragraphs:
        para = para.strip()
        if not para:
            continue

        # Check if it's a list block
        lines = para.split('\n')
        is_list = all(line.strip().startswith('- ') or line.strip() == '' for line in lines)

        if is_list:
            for line in lines:
                line = line.strip()
                if line.startswith('- '):
                    bullet_text = line[2:]
                    pdf.set_font("Helvetica", "", 10)
                    pdf.set_text_color(50, 50, 50)
                    # Indent for bullet
                    x = pdf.get_x()
                    pdf.set_x(x + 6)
                    pdf.multi_cell(pdf.w - pdf.r_margin - pdf.get_x(), 5,
                                   f"\u2022  {bullet_text}")
                    pdf.ln(1)
        else:
            # Regular paragraph — join lines
            joined = ' '.join(line.strip() for line in lines)
            pdf.multi_cell(0, 5, joined)
            pdf.ln(3)


# ── LaTeX generation ────────────────────────────────────────────────────────

def _escape_latex(text: str) -> str:
    """Escape special LaTeX characters."""
    replacements = [
        ('\\', '\\textbackslash{}'),
        ('&', '\\&'),
        ('%', '\\%'),
        ('$', '\\$'),
        ('#', '\\#'),
        ('_', '\\_'),
        ('{', '\\{'),
        ('}', '\\}'),
        ('~', '\\textasciitilde{}'),
        ('^', '\\textasciicircum{}'),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def _md_to_latex(text: str) -> str:
    """Convert markdown content to LaTeX."""
    # Bold
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'\\textbf{\\textit{\1}}', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'\\textbf{\1}', text)
    text = re.sub(r'\*(.+?)\*', r'\\textit{\1}', text)
    # Headers within content → subsections
    text = re.sub(r'^###\s+(.+)$', r'\\subsubsection*{\1}', text, flags=re.MULTILINE)
    text = re.sub(r'^##\s+(.+)$', r'\\subsection*{\1}', text, flags=re.MULTILINE)
    text = re.sub(r'^#\s+(.+)$', r'\\section*{\1}', text, flags=re.MULTILINE)
    # Inline code
    text = re.sub(r'`([^`]+)`', r'\\texttt{\1}', text)
    # Links
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'\\href{\2}{\1}', text)
    # Blockquotes
    text = re.sub(r'^>\s?(.+)$', r'\\begin{quote}\1\\end{quote}', text, flags=re.MULTILINE)

    # Convert bullet lists
    lines = text.split('\n')
    result = []
    in_list = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('- '):
            if not in_list:
                result.append('\\begin{itemize}')
                in_list = True
            item_text = stripped[2:]
            result.append(f'  \\item {item_text}')
        else:
            if in_list:
                result.append('\\end{itemize}')
                in_list = False
            result.append(line)
    if in_list:
        result.append('\\end{itemize}')

    return '\n'.join(result)


def generate_latex(data: dict) -> str:
    """Generate a LaTeX document from report data. Returns .tex string."""
    report = _get_report(data)
    if not report:
        raise ValueError("No report data found")

    meta = report.get("metadata", {})
    sections = report.get("sections", [])
    disclaimer_items = report.get("disclaimer_items", [])

    project_name = "Environmental Assessment"
    for s in sections:
        if s.get("section_number") == "1" and s.get("content"):
            match = re.search(r'\*\*Project:\*\*\s*(.+)', s["content"])
            if match:
                project_name = match.group(1).strip()
                break

    framework = f"{report.get('framework_id', 'NEPA')} {report.get('document_type', 'EA')}"
    gen_date = meta.get("generated_at", "")
    if gen_date:
        try:
            dt = datetime.fromisoformat(gen_date.replace("Z", "+00:00"))
            gen_date = dt.strftime("%B %d, %Y")
        except (ValueError, TypeError):
            pass

    model = meta.get("llm_model_used", "")

    tex = []
    tex.append(r"""\documentclass[11pt,letterpaper]{article}

\usepackage[margin=1in]{geometry}
\usepackage{titlesec}
\usepackage{parskip}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{enumitem}

% Header/footer
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\textcolor{gray}{""" + _escape_latex(project_name) + r"""}}
\fancyhead[R]{\small\textcolor{gray}{Environmental Assessment}}
\fancyfoot[C]{\small\thepage}
\renewcommand{\headrulewidth}{0.4pt}

% Section formatting
\titleformat{\section}{\Large\bfseries}{}{0em}{}[\vspace{-0.5em}\rule{\textwidth}{0.4pt}]
\titleformat{\subsection}{\large\bfseries}{}{0em}{}
\titleformat{\subsubsection}{\normalsize\bfseries}{}{0em}{}

\hypersetup{
    colorlinks=true,
    linkcolor=blue!60!black,
    urlcolor=blue!60!black,
}

\begin{document}

% ── Title Page ──────────────────────────────────────────────────
\begin{titlepage}
\centering
\vspace*{3cm}
{\Huge\bfseries Environmental Assessment\par}
\vspace{0.5cm}
\rule{0.6\textwidth}{0.4pt}
\vspace{0.5cm}
{\Large """ + _escape_latex(project_name) + r"""\par}
\vspace{1cm}
{\normalsize Framework: """ + _escape_latex(framework) + r"""\par}""")

    if gen_date:
        tex.append(r"{\normalsize Generated: " + _escape_latex(gen_date) + r"\par}")
    if model:
        tex.append(r"{\normalsize Model: " + _escape_latex(model) + r"\par}")

    tex.append(r"""
\vfill
{\small\textit{This document was generated by an automated environmental screening
system. All determinations should be reviewed by a qualified environmental
professional before use in regulatory submissions.}}
\end{titlepage}

% ── Table of Contents ───────────────────────────────────────────
\tableofcontents
\newpage
""")

    # ── Sections ────────────────────────────────────────────────────
    for s in sections:
        num = s.get("section_number", "")
        title = s.get("section_title", "Untitled")
        content = s.get("content", "")
        highlights = s.get("low_confidence_highlights", [])

        safe_title = _escape_latex(title)
        tex.append(f"\n\\section{{{num}. {safe_title}}}")

        # Convert markdown content to LaTeX
        if content:
            latex_content = _md_to_latex(content)
            tex.append(latex_content)

        # Low-confidence highlights
        if highlights:
            tex.append(r"\vspace{0.5em}")
            tex.append(r"\noindent\textbf{\textcolor{orange}{Low Confidence Items:}}")
            tex.append(r"\begin{itemize}[leftmargin=1.5em]")
            for h in highlights:
                conf = round((h.get("confidence", 0)) * 100)
                excerpt = _escape_latex(h.get("text_excerpt", ""))
                tex.append(f"  \\item \\textcolor{{orange}}{{[{conf}\\%]}} {excerpt}")
            tex.append(r"\end{itemize}")

        tex.append(r"\newpage")

    # ── Disclaimer appendix ─────────────────────────────────────────
    if disclaimer_items:
        tex.append(r"\section{Items Requiring Human Review}")
        for item in disclaimer_items:
            cat = _escape_latex((item.get("category", "") or "").replace("_", " "))
            det = _escape_latex(item.get("determination", ""))
            conf = round((item.get("confidence", 0)) * 100)
            reasoning = _escape_latex(item.get("reasoning", ""))

            tex.append(f"\n\\noindent\\textbf{{{cat}}} --- {det} ({conf}\\% confidence)")
            if reasoning:
                tex.append(f"\n\\begin{{quote}}\\small {reasoning}\\end{{quote}}")

    tex.append(r"""
\end{document}
""")

    return '\n'.join(tex)
